-- Insertion des exercices de base
INSERT INTO exercises (name, description, category, difficulty, equipment, muscles_primary, muscles_secondary, instructions, tips)
VALUES
  ('Tapis de course', 'Marche rapide ou jogging léger sur tapis de course', 'Cardio', 'Débutant', ARRAY['Tapis de course'], ARRAY['Jambes', 'Système cardiovasculaire'], ARRAY['Core'], 'Marchez ou courez à un rythme confortable sur le tapis de course.', 'Gardez une bonne posture et balancez naturellement les bras.'),
  ('Vélo elliptique', 'Exercice cardiovasculaire à faible impact', 'Cardio', 'Débutant', ARRAY['Vélo elliptique'], ARRAY['Jambes', 'Système cardiovasculaire'], ARRAY['Bras', 'Core'], 'Placez vos pieds sur les pédales et commencez à pédaler en tenant les poignées.', 'Maintenez le dos droit et engagez les muscles abdominaux.'),
  ('Squat à la barre', 'Exercice polyarticulaire ciblant principalement les jambes', 'Jambes', 'Intermédiaire', ARRAY['Barre', 'Rack à squat'], ARRAY['Quadriceps', 'Fessiers'], ARRAY['Ischio-jambiers', 'Lombaires'], 'Placez la barre sur vos trapèzes, descendez en pliant les genoux jusqu''à ce que vos cuisses soient parallèles au sol, puis remontez.', 'Gardez le dos droit et les genoux alignés avec les orteils.'),
  ('Développé couché', 'Exercice de poussée horizontale pour la poitrine', 'Poitrine', 'Intermédiaire', ARRAY['Barre', 'Banc'], ARRAY['Pectoraux'], ARRAY['Triceps', 'Épaules'], 'Allongez-vous sur un banc, descendez la barre jusqu''à la poitrine, puis poussez vers le haut.', 'Gardez les poignets droits et les coudes à un angle de 45 degrés.'),
  ('Rowing à la barre', 'Exercice de tirage pour le dos', 'Dos', 'Intermédiaire', ARRAY['Barre'], ARRAY['Dorsaux', 'Rhomboïdes'], ARRAY['Biceps', 'Avant-bras'], 'Penchez-vous en avant, tirez la barre vers votre abdomen, puis redescendez lentement.', 'Gardez le dos droit et les épaules basses.'),
  ('Développé militaire', 'Exercice de poussée verticale pour les épaules', 'Épaules', 'Intermédiaire', ARRAY['Barre', 'Haltères'], ARRAY['Deltoïdes'], ARRAY['Triceps', 'Trapèzes'], 'En position debout ou assise, poussez la barre ou les haltères au-dessus de votre tête, puis redescendez.', 'Évitez de cambrer le dos et gardez les abdominaux engagés.'),
  ('Fentes avec haltères', 'Exercice unilatéral pour les jambes', 'Jambes', 'Intermédiaire', ARRAY['Haltères'], ARRAY['Quadriceps', 'Fessiers'], ARRAY['Ischio-jambiers', 'Core'], 'Tenez un haltère dans chaque main, faites un pas en avant, pliez les genoux, puis revenez à la position initiale.', 'Gardez le torse droit et le genou avant aligné avec le pied.'),
  ('Gainage (planche)', 'Exercice statique pour renforcer le core', 'Abdominaux', 'Débutant', ARRAY['Aucun'], ARRAY['Abdominaux', 'Core'], ARRAY['Épaules', 'Fessiers'], 'Placez-vous en position de planche sur les avant-bras, maintenez la position en gardant le corps aligné.', 'Engagez les abdominaux et ne laissez pas le bassin s''affaisser.'),
  ('Presse à cuisses', 'Exercice guidé pour les jambes', 'Jambes', 'Débutant', ARRAY['Machine presse à cuisses'], ARRAY['Quadriceps', 'Fessiers'], ARRAY['Ischio-jambiers'], 'Asseyez-vous sur la machine, poussez la plateforme avec vos pieds, puis pliez lentement les genoux pour revenir.', 'Ne verrouillez pas complètement les genoux en position haute.'),
  ('Leg extensions', 'Exercice d''isolation pour les quadriceps', 'Jambes', 'Débutant', ARRAY['Machine leg extensions'], ARRAY['Quadriceps'], ARRAY[]::text[], 'Asseyez-vous sur la machine, étendez les jambes pour soulever le poids, puis revenez lentement.', 'Évitez de verrouiller les genoux et contrôlez le mouvement.');
