-- Insertion des exercices supplémentaires
INSERT INTO exercises (name, description, category, difficulty, equipment, muscles_primary, muscles_secondary, instructions, tips)
VALUES
  ('Leg curls', 'Exercice d''isolation pour les ischio-jambiers', 'Jambes', 'Débutant', ARRAY['Machine leg curls'], ARRAY['Ischio-jambiers'], ARRAY[]::text[], 'Allongez-vous sur la machine, pliez les jambes pour soulever le poids, puis revenez lentement.', 'Contrôlez le mouvement dans les deux directions.'),
  ('Mollets à la machine', 'Exercice d''isolation pour les mollets', 'Jambes', 'Débutant', ARRAY['Machine mollets', 'Haltères'], ARRAY['Mollets'], ARRAY[]::text[], 'Placez-vous sur la machine, montez sur la pointe des pieds, puis redescendez lentement.', 'Effectuez une extension complète et une flexion complète.'),
  ('Crunchs', 'Exercice d''isolation pour les abdominaux', 'Abdominaux', 'Débutant', ARRAY['Aucun', 'Machine abdominaux'], ARRAY['Abdominaux'], ARRAY[]::text[], 'Allongez-vous sur le dos, pliez les genoux, soulevez les épaules du sol en contractant les abdominaux.', 'Concentrez-vous sur la contraction des abdominaux plutôt que sur l''amplitude.'),
  ('Relevés de jambes', 'Exercice pour les abdominaux inférieurs', 'Abdominaux', 'Intermédiaire', ARRAY['Aucun'], ARRAY['Abdominaux inférieurs'], ARRAY['Fléchisseurs de hanches'], 'Allongez-vous sur le dos, soulevez les jambes tendues vers le plafond, puis redescendez sans toucher le sol.', 'Gardez le bas du dos plaqué au sol.'),
  ('Gainage latéral', 'Exercice statique pour les obliques', 'Abdominaux', 'Intermédiaire', ARRAY['Aucun'], ARRAY['Obliques', 'Core'], ARRAY['Épaules'], 'Placez-vous sur le côté en appui sur un avant-bras, soulevez les hanches pour former une ligne droite.', 'Gardez le corps aligné et ne laissez pas les hanches s''affaisser.'),
  ('Rameur', 'Exercice cardiovasculaire complet', 'Cardio', 'Débutant', ARRAY['Rameur'], ARRAY['Dos', 'Jambes', 'Système cardiovasculaire'], ARRAY['Bras', 'Core'], 'Asseyez-vous sur le rameur, poussez avec les jambes, tirez avec les bras, puis revenez à la position initiale.', 'Commencez le mouvement par les jambes, puis enchaînez avec le dos et les bras.'),
  ('Tirage vertical', 'Exercice de tirage vertical pour le dos', 'Dos', 'Intermédiaire', ARRAY['Machine tirage vertical'], ARRAY['Dorsaux'], ARRAY['Biceps', 'Avant-bras'], 'Asseyez-vous à la machine, saisissez la barre, tirez vers le bas jusqu''à la poitrine, puis remontez lentement.', 'Gardez le dos droit et les épaules basses.'),
  ('Développé incliné avec haltères', 'Exercice de poussée pour la partie supérieure de la poitrine', 'Poitrine', 'Intermédiaire', ARRAY['Haltères', 'Banc incliné'], ARRAY['Pectoraux supérieurs'], ARRAY['Triceps', 'Épaules'], 'Allongez-vous sur un banc incliné, poussez les haltères vers le haut, puis redescendez.', 'Gardez les poignets droits et les coudes à un angle de 45 degrés.'),
  ('Élévations latérales', 'Exercice d''isolation pour les deltoïdes latéraux', 'Épaules', 'Débutant', ARRAY['Haltères'], ARRAY['Deltoïdes latéraux'], ARRAY[]::text[], 'Tenez un haltère dans chaque main, soulevez-les latéralement jusqu''à l''horizontale, puis redescendez.', 'Gardez les coudes légèrement fléchis et évitez de hausser les épaules.'),
  ('Biceps curl avec haltères', 'Exercice d''isolation pour les biceps', 'Bras', 'Débutant', ARRAY['Haltères'], ARRAY['Biceps'], ARRAY['Avant-bras'], 'Tenez un haltère dans chaque main, fléchissez les coudes pour soulever les haltères, puis redescendez.', 'Gardez les coudes près du corps et évitez de balancer le torse.'),
  ('Triceps extensions', 'Exercice d''isolation pour les triceps', 'Bras', 'Débutant', ARRAY['Poulie haute'], ARRAY['Triceps'], ARRAY[]::text[], 'Saisissez la corde ou la barre de la poulie haute, étendez les bras vers le bas, puis revenez à la position initiale.', 'Gardez les coudes près de la tête et concentrez-vous sur la contraction des triceps.');
